/**
 * Deployment records are per-INSTANCE, and the live one must be unlosable.
 *
 * ⛔ WHAT THIS PREVENTS. `deployment-preview.json` was a single file that both
 * preview deploy scripts wrote unconditionally. Standing up a second protocol
 * instance on the same network — which the alpha.3 migration requires, since
 * alpha.3 goes up BESIDE the live alpha.2 instance rather than replacing it —
 * would have silently overwritten the first. And a deployment record is not a
 * build artifact: its bootstrap seed UTxOs are one-shot and already spent, so a
 * lost record cannot be regenerated by re-running anything.
 *
 * The two behaviours under test are both REFUSALS, because both failure modes
 * are silent by nature:
 *   - there is NO default instance (a default is what made "which instance?" an
 *     invisible question), and
 *   - save REFUSES to overwrite unless the caller says so explicitly.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { rmSync, existsSync } from "node:fs";

import {
  instancePath,
  listInstances,
  loadInstance,
  saveInstance,
  requireInstanceName,
} from "./harness/instances.mjs";

// ---------------------------------------------------------------------------
// The live record
// ---------------------------------------------------------------------------

test("the live alpha.2 preview instance survived the move and is loadable", () => {
  const dep = loadInstance("preview", "alpha2");

  // Pinned to the real deployment. If this changes, a live protocol instance's
  // record changed, and that is never an incidental edit.
  assert.equal(
    dep.txHash,
    "35954fc8c92db95dc7d1de361da3fe7d6ad0f6711f9501ebf7d7cf4219262031",
    "the bootstrap tx of the live preview deployment",
  );
  assert.equal(
    dep.programmableLogicBase.scriptHash,
    "5f9ee621c098be5d3a8d7bf8579267cc949c197ece726daa0e8a446f",
  );
  assert.equal(dep.upgradeAuthority.type, "key");
  assert.equal(
    dep.upgradeAuthority.hash,
    "219ad1301592c6e16b74c49b1b1f8ffdf7e87e22a85c8e63bbed49cf",
  );
  // Four reference-script UTxOs, all from the same publish transaction.
  for (const k of [
    "programmableBaseRefInput",
    "transferRefInput",
    "thirdPartyRefInput",
    "unfrackingRefInput",
  ]) {
    assert.equal(
      dep[k].txHash,
      "e466d078444a4d750ccb99f4ebc1d22957772ff49bb53a0228e0ce45f5c6e479",
      `${k} must still name the live reference-script tx`,
    );
  }
});

test("it is listed under preview", () => {
  assert.ok(listInstances("preview").includes("alpha2"));
});

// ---------------------------------------------------------------------------
// Refusals
// ---------------------------------------------------------------------------

test("an unknown instance names what IS available", () => {
  assert.throws(
    () => loadInstance("preview", "does-not-exist"),
    (e) => {
      assert.match(e.message, /No preview instance named "does-not-exist"/);
      assert.match(e.message, /alpha2/, "must list what exists — the fix is usually a typo");
      return true;
    },
  );
});

test("there is NO default instance", () => {
  // The whole point: absent a name, fail loudly rather than pick one.
  assert.throws(
    () => requireInstanceName("preview", ["node", "script"]),
    (e) => {
      assert.match(e.message, /No instance named/);
      assert.match(e.message, /alpha2/);
      assert.match(e.message, /deliberately no default/);
      return true;
    },
  );
});

test("--instance and CIP113_INSTANCE both resolve", () => {
  assert.equal(requireInstanceName("preview", ["node", "s", "--instance", "alpha3"]), "alpha3");

  const prev = process.env.CIP113_INSTANCE;
  process.env.CIP113_INSTANCE = "from-env";
  try {
    assert.equal(requireInstanceName("preview", ["node", "s"]), "from-env");
    // argv wins over env — an explicit flag is the more specific intention.
    assert.equal(requireInstanceName("preview", ["node", "s", "--instance", "from-argv"]), "from-argv");
  } finally {
    if (prev === undefined) delete process.env.CIP113_INSTANCE;
    else process.env.CIP113_INSTANCE = prev;
  }
});

test("a name that would escape the deployments directory is refused", () => {
  // The name becomes a filename; traversal would write anywhere on disk.
  for (const bad of ["../escape", "a/b", "/abs", "..", "", "with space"]) {
    assert.throws(() => instancePath("preview", bad), /Invalid instance name/, `should refuse ${JSON.stringify(bad)}`);
  }
  assert.ok(instancePath("preview", "alpha3.rc1").endsWith("alpha3.rc1.json"));
});

// ---------------------------------------------------------------------------
// Overwrite protection — pid-scoped scratch names under devnet, never preview
// ---------------------------------------------------------------------------

test("save REFUSES to clobber an existing instance, and says why", () => {
  // A pid-scoped scratch name under devnet, cleaned up in `finally`. Never the
  // preview tree — these tests must not be able to touch a live record.
  const NET = "devnet";
  const name = "scratch-" + process.pid;
  const target = instancePath(NET, name);
  assert.ok(!existsSync(target), "precondition: the scratch instance must not exist");

  try {
    saveInstance(NET, name, { txHash: "aa" });
    assert.deepEqual(loadInstance(NET, name), { txHash: "aa" });

    // The refusal.
    assert.throws(
      () => saveInstance(NET, name, { txHash: "bb" }),
      (e) => {
        assert.match(e.message, /Refusing to overwrite/);
        assert.match(e.message, /one-shot and already spent/, "must say why it cannot be regenerated");
        return true;
      },
    );
    // …and the original is untouched.
    assert.deepEqual(loadInstance(NET, name), { txHash: "aa" });

    // Explicit intent goes through.
    saveInstance(NET, name, { txHash: "bb" }, { overwrite: true });
    assert.deepEqual(loadInstance(NET, name), { txHash: "bb" });
  } finally {
    rmSync(target, { force: true });
  }
});

test("bigints in a deployment record serialise rather than throwing", () => {
  // The bootstrap's own arithmetic produces bigints; JSON.stringify throws on
  // them by default, and it throws for the WHOLE document, not the one field.
  const NET = "devnet";
  const name = "scratch-bigint-" + process.pid;
  const target = instancePath(NET, name);
  try {
    saveInstance(NET, name, { lovelace: 3_000_000n, nested: { q: 1n } });
    assert.deepEqual(loadInstance(NET, name), { lovelace: "3000000", nested: { q: "1" } });
  } finally {
    rmSync(target, { force: true });
  }
});
