/**
 * Deployment instances — test/harness state, never shipped.
 *
 * ⛔ WHY THIS EXISTS RATHER THAN ONE `deployment-preview.json`. That file was
 * SINGULAR, and both preview deploy scripts wrote to it unconditionally. The
 * moment a second protocol instance exists on the same network — which is
 * exactly what the alpha.3 migration requires, since alpha.3 must stand up
 * BESIDE the live alpha.2 instance rather than replace it — the second deploy
 * silently overwrites the first. The record of a LIVE deployment, whose
 * reference scripts and genesis UTxOs are still on chain and which a consuming
 * platform is pointed at, would be gone with no error and no diff to read.
 *
 * A deployment record is not a build artifact. It is the only off-chain
 * description of on-chain state that cannot be regenerated: its bootstrap seed
 * UTxOs are one-shot and already spent, so a lost record cannot be recovered by
 * re-running anything. (It CAN be partially reconstructed from the chain — that
 * was done once, 2026-08-31, and it cost a session.)
 *
 * Two deliberate refusals here, both learned rather than assumed:
 *
 *   1. THERE IS NO DEFAULT INSTANCE. A default is how the singular file failed:
 *      it made "which instance?" an invisible question with a silent answer.
 *      Callers name the instance; a missing name is an error that lists what
 *      exists.
 *   2. SAVE REFUSES TO OVERWRITE. Creating a new instance and updating an
 *      existing one are different intentions, and only one of them can destroy
 *      a live record. The caller must say which.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");

/**
 * Networks an instance may live on. Mainnet is deliberately absent.
 * @typedef {"preview" | "devnet"} InstanceNetwork
 */

function instanceDir(/** @type {InstanceNetwork} */ network) {
  return resolve(ROOT, "deployments", network);
}

/** Path of one named instance's record. */
export function instancePath(/** @type {InstanceNetwork} */ network, /** @type {string} */ name) {
  if (!/^[a-z0-9][a-z0-9._-]*$/i.test(name)) {
    throw new Error(
      `Invalid instance name ${JSON.stringify(name)}. Use letters, digits, dot, dash or ` +
        `underscore — the name becomes a filename.`
    );
  }
  return resolve(instanceDir(network), `${name}.json`);
}

/** Names of every recorded instance on a network, sorted. */
export function listInstances(/** @type {InstanceNetwork} */ network) {
  const dir = instanceDir(network);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .map((f) => f.slice(0, -".json".length))
    .sort();
}

/**
 * Load one instance's DeploymentParams.
 *
 * The error names what IS available, per this repo's habit — an unknown
 * instance is usually a typo, and the fix is visible in the list.
 */
export function loadInstance(/** @type {InstanceNetwork} */ network, /** @type {string} */ name) {
  const path = instancePath(network, name);
  if (!existsSync(path)) {
    const known = listInstances(network);
    throw new Error(
      `No ${network} instance named "${name}" (looked in ${path}). ` +
        (known.length > 0
          ? `Known ${network} instances: ${known.join(", ")}.`
          : `No ${network} instances are recorded yet.`)
    );
  }
  return JSON.parse(readFileSync(path, "utf-8"));
}

/**
 * Write one instance's DeploymentParams.
 *
 * ⚠ Refuses to clobber by default. Pass `{ overwrite: true }` only when
 * updating an instance you intend to replace — never to "make the deploy script
 * work". If a deploy is genuinely creating a new instance, give it a new name.
 */
export function saveInstance(
  /** @type {InstanceNetwork} */ network,
  /** @type {string} */ name,
  /** @type {unknown} */ deployment,
  /** @type {{ overwrite?: boolean }} */ opts = {}
) {
  const path = instancePath(network, name);
  if (existsSync(path) && !opts.overwrite) {
    throw new Error(
      `Refusing to overwrite the existing ${network} instance "${name}" (${path}). ` +
        `Its bootstrap seed UTxOs are one-shot and already spent, so this record cannot be ` +
        `regenerated by re-running the deploy. Choose a new instance name, or pass ` +
        `{ overwrite: true } if you really mean to replace it.`
    );
  }
  mkdirSync(instanceDir(network), { recursive: true });
  // bigints reach here from the bootstrap's own arithmetic; JSON cannot encode
  // them and would throw on the whole document rather than the offending field.
  writeFileSync(
    path,
    JSON.stringify(deployment, (_k, v) => (typeof v === "bigint" ? v.toString() : v), 2) + "\n"
  );
  return path;
}

/**
 * Resolve the instance a harness script should act on, from argv or env.
 *
 * Accepts `--instance <name>` or `CIP113_INSTANCE=<name>`. Absent both, it
 * FAILS and lists what exists rather than picking one.
 */
export function requireInstanceName(/** @type {InstanceNetwork} */ network, /** @type {string[]} */ argv = process.argv) {
  const flag = argv.indexOf("--instance");
  const fromArgv = flag >= 0 ? argv[flag + 1] : undefined;
  const name = fromArgv ?? process.env.CIP113_INSTANCE;
  if (!name) {
    const known = listInstances(network);
    throw new Error(
      `No instance named. Pass --instance <name> or set CIP113_INSTANCE. ` +
        (known.length > 0
          ? `Known ${network} instances: ${known.join(", ")}. `
          : `No ${network} instances are recorded yet. `) +
        `There is deliberately no default: a default is how a second deployment silently ` +
        `overwrote the first.`
    );
  }
  return name;
}
