import "dotenv/config";
import { readFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import {
  evoClient,
  preprodChain,
  previewChain,
  mainnetChain,
  paymentCredentialHash,
  EvoAddress,
  type PlutusBlueprint,
} from "@easy1staking/cip113-sdk-ts";
import type { DeploymentParams } from "@easy1staking/cip113-sdk-ts";
import type { Chain } from "@evolution-sdk/evolution";
import { getYaciChain } from "./yaci.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ---------------------------------------------------------------------------
// Environment
// ---------------------------------------------------------------------------

export type Network = "preprod" | "preview" | "mainnet" | "yaci";

export function getEnv(key: string, required = true): string {
  const val = process.env[key];
  if (!val && required) {
    console.error(`Missing required env var: ${key}`);
    console.error("Copy .env.example to .env and fill in your values.");
    process.exit(1);
  }
  return val ?? "";
}

export function getNetwork(): Network {
  return (getEnv("NETWORK", false) || "preprod") as Network;
}

export function isYaci(): boolean {
  return getNetwork() === "yaci";
}

async function resolveChain(): Promise<Chain> {
  const n = getNetwork();
  if (n === "yaci") return getYaciChain();
  if (n === "preview") return previewChain;
  if (n === "mainnet") return mainnetChain;
  return preprodChain;
}

// ---------------------------------------------------------------------------
// Evolution SDK Client
// ---------------------------------------------------------------------------

export async function createSigningClient(mnemonic?: string) {
  const chain = await resolveChain();
  const seed = mnemonic || getEnv("WALLET_MNEMONIC");

  if (isYaci()) {
    const provider = getEnv("YACI_PROVIDER", false) || "kupmios";
    if (provider === "blockfrost") {
      const baseUrl = getEnv("BLOCKFROST_URL", false) || "http://localhost:8080/api/v1";
      return evoClient(chain)
        .withBlockfrost({ projectId: "dummy", baseUrl })
        .withSeed({ mnemonic: seed });
    }
    const kupoUrl = getEnv("KUPO_URL", false) || "http://localhost:1442";
    const ogmiosUrl = getEnv("OGMIOS_URL", false) || "http://localhost:1337";
    return evoClient(chain)
      .withKupmios({ kupoUrl, ogmiosUrl })
      .withSeed({ mnemonic: seed });
  }

  const network = getNetwork();
  const projectId = getEnv("BLOCKFROST_PROJECT_ID");
  const baseUrl =
    getEnv("BLOCKFROST_URL", false) ||
    `https://cardano-${network}.blockfrost.io/api/v0`;

  return evoClient(chain)
    .withBlockfrost({ projectId, baseUrl })
    .withSeed({ mnemonic: seed });
}

export async function createSecondClient() {
  const second = getEnv("SECOND_WALLET_MNEMONIC", false);
  if (!second) return null;
  return createSigningClient(second);
}

type SigningClient = Awaited<ReturnType<typeof createSigningClient>>;

export async function getWalletAddress(client: SigningClient): Promise<string> {
  const addr = await client.address();
  return EvoAddress.toBech32(addr);
}

export function getAdminPkh(address: string): string {
  return paymentCredentialHash(address);
}

// ---------------------------------------------------------------------------
// Blueprints
// ---------------------------------------------------------------------------

function loadJson(relativePath: string): PlutusBlueprint {
  const fullPath = resolve(__dirname, "..", "..", relativePath);
  return JSON.parse(readFileSync(fullPath, "utf-8"));
}

export function loadStandardBlueprint(): PlutusBlueprint {
  return loadJson("blueprints/standard/v0.3.0/plutus.json");
}

export function loadFESBlueprint(): PlutusBlueprint {
  return loadJson("blueprints/substandards/freeze-and-seize/v0.1.0/plutus.json");
}

export function loadDummyBlueprint(): PlutusBlueprint {
  return loadJson("blueprints/substandards/dummy/v0.1.0/plutus.json");
}

export function loadBaFinBlueprint(): PlutusBlueprint {
  return loadJson("blueprints/substandards/bafin/v0.2.0/plutus.json");
}

// ---------------------------------------------------------------------------
// Deployment Params
// ---------------------------------------------------------------------------

/** @deprecated Use loadDeployment() instead */
export const PREPROD_DEPLOYMENT: DeploymentParams = JSON.parse(
  readFileSync(resolve(__dirname, "deployment-preprod.json"), "utf-8"),
);

/**
 * Load CIP-113 standard deployment params from a JSON file matching the current network.
 * Files: deployment-preprod.json, deployment-preview.json, deployment-mainnet.json,
 * deployment-yaci.json (generated by bafin/00-deploy-standard.ts).
 */
export function loadDeployment(): DeploymentParams {
  const network = getNetwork();
  const fullPath = resolve(__dirname, `deployment-${network}.json`);
  return JSON.parse(readFileSync(fullPath, "utf-8"));
}

export function getTokenName(): string {
  const custom = getEnv("TOKEN_NAME", false);
  if (custom) return custom;
  // Generate a unique name per run so repeated runs don't collide
  const ts = Date.now().toString(36).slice(-4).toUpperCase();
  return `DEMO-${ts}`;
}

/**
 * Check if a stake address is registered on-chain.
 * On public networks: queries Blockfrost.
 * On Yaci: queries the Yaci Store Blockfrost-compatible API directly.
 */
export async function checkStakeRegistration(stakeAddress: string): Promise<boolean> {
  const baseUrl = isYaci()
    ? getEnv("BLOCKFROST_URL", false) || "http://localhost:8080/api/v1"
    : getEnv("BLOCKFROST_URL", false) ||
      `https://cardano-${getNetwork()}.blockfrost.io/api/v0`;

  const headers: Record<string, string> = {};
  if (!isYaci()) {
    headers.project_id = getEnv("BLOCKFROST_PROJECT_ID");
  }

  try {
    const res = await fetch(`${baseUrl}/accounts/${stakeAddress}`, { headers });
    return res.ok; // 200 = registered, 404 = not registered
  } catch {
    return false;
  }
}
